// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pokedex.Repository;

#nullable disable

namespace Pokedex.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pokedex.Core.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrainerId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Pokemons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A strange seed was planted on its back at birth. The plant sprouts and grows with this POKéMON.",
                            Name = "Bulbasaur",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2367),
                            TrainerId = 1,
                            Type = "Grass"
                        },
                        new
                        {
                            Id = 2,
                            Description = "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
                            Name = "Ivysaur",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2379),
                            TrainerId = 1,
                            Type = "Grass"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
                            Name = "Venusaur",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2381),
                            TrainerId = 1,
                            Type = "Grass"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.",
                            Name = "Charmander",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2382),
                            TrainerId = 1,
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 5,
                            Description = "When it swings its burning tail, it elevates the temperature to unbearably high levels.",
                            Name = "Charmeleon",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2384),
                            TrainerId = 2,
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
                            Name = "Charizard",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2386),
                            TrainerId = 2,
                            Type = "Fire"
                        },
                        new
                        {
                            Id = 7,
                            Description = "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.",
                            Name = "Squirtle",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2387),
                            TrainerId = 2,
                            Type = "Water"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.",
                            Name = "Wartortle",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2389),
                            TrainerId = 2,
                            Type = "Water"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A brutal POKéMON with pressurized water jets on its shell. They are used for high-speed tackles.",
                            Name = "Blastoise",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2390),
                            TrainerId = 3,
                            Type = "Water"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
                            Name = "Caterpie",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2392),
                            TrainerId = 3,
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 11,
                            Description = "This POKéMON is vulnerable to attack while its shell is soft, exposing its weak and tender body.",
                            Name = "Metapod",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2393),
                            TrainerId = 3,
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 12,
                            Description = "In battle, it flaps its wings at great speed to release highly toxic dust into the air.",
                            Name = "Butterfree",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2395),
                            TrainerId = 3,
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.",
                            Name = "Weedle",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2396),
                            TrainerId = 4,
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Almost incapable of moving, this POKéMON can only harden its shell to protect itself from predators.",
                            Name = "Kakuna",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2398),
                            TrainerId = 4,
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Flies at high speed and attacks using its large venomous stingers on its forelegs and tail.",
                            Name = "Beedrill",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2399),
                            TrainerId = 4,
                            Type = "Bug"
                        },
                        new
                        {
                            Id = 16,
                            Description = "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.",
                            Name = "Pidgey",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2400),
                            TrainerId = 4,
                            Type = "Flying"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Very protective of its sprawling territorial area, this POKéMON will fiercely peck at any intruder.",
                            Name = "Pidgeotto",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2402),
                            TrainerId = 5,
                            Type = "Flying"
                        },
                        new
                        {
                            Id = 18,
                            Description = "This POKéMON flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons.",
                            Name = "Pidgeot",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2403),
                            TrainerId = 5,
                            Type = "Flying"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
                            Name = "Rattata",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2404),
                            TrainerId = 5,
                            Type = "Normal"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey.",
                            Name = "Raticate",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2406),
                            TrainerId = 5,
                            Type = "Normal"
                        });
                });

            modelBuilder.Entity("Pokedex.Core.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Trainers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ash Ketchum",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2719)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Misty",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2722)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Brock",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2724)
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gary Oak",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2725)
                        },
                        new
                        {
                            Id = 5,
                            Name = "Red",
                            RegisteredDate = new DateTime(2023, 8, 1, 14, 3, 56, 358, DateTimeKind.Local).AddTicks(2726)
                        });
                });

            modelBuilder.Entity("Pokedex.Core.Models.Pokemon", b =>
                {
                    b.HasOne("Pokedex.Core.Models.Trainer", "Trainer")
                        .WithMany("Pokemons")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Pokedex.Core.Models.Trainer", b =>
                {
                    b.Navigation("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
